/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pomodorogui;

import java.awt.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jose26398
 */
public class Asignaciones extends javax.swing.JFrame {
    Statement stmt;
    String var;
    int tipo;
    ArrayList<JCheckBox> checks = new ArrayList();

    
    /**
     * Creates new form MenuContienePlato
     */
    public Asignaciones(ArrayList<String> list, String var, Statement stmt, int tipo) {
        this.setVisible(true);
        initComponents();
        this.stmt = stmt;
        this.var = var;
        this.tipo = tipo;
        
        jPanel1.setLayout(new GridLayout(0, 1));
        for(int i=0; i<list.size(); i++){
            checks.add( new JCheckBox(list.get(i)) );
            jPanel1.add( checks.get(i) );
        }
        
        add(jPanel1, BorderLayout.LINE_START);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void menuContienePlato(String valores){
        try {
            stmt.executeUpdate("insert into menu_contiene_plato (id_menu, cod_plato) "+
                               "values"+valores);
            JOptionPane.showMessageDialog(this, "Query OK");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }        
    }
    
    public void platoContieneIngrediente(String valores){
        try {
            stmt.executeUpdate("insert into plato_contiene_ing (cod_plato, cod_ing) "+
                               "values"+valores);
            JOptionPane.showMessageDialog(this, "Query OK");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }        
    }
    
    public void establecerIngrediente(String valores){
        try {
            stmt.executeUpdate("insert into provee (dni_prov, cod_ing) "+
                               "values"+valores);
            JOptionPane.showMessageDialog(this, "Query OK");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAceptarMcP = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonAceptarMcP.setText("Aceptar");
        BotonAceptarMcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarMcPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccionar Variables");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAceptarMcP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAceptarMcP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarMcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarMcPActionPerformed
        String valores = "";
        for (int i=0; i < checks.size(); i++) {
            if ( checks.get(i).isSelected() )
                valores += "('"+var+"','"+checks.get(i).getText()+ "'),";
        }
        valores = valores.substring(0, valores.length() - 1);
        
        switch (tipo) {
            case 1:
                menuContienePlato(valores);
                break;
            case 2:
                platoContieneIngrediente(valores);
                break;
            case 3:
                establecerIngrediente(valores);
                break;
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_BotonAceptarMcPActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptarMcP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
