/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pomodorogui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author jose26398
 */
public class PomodoroGUI extends javax.swing.JFrame {
    
    static PomodoroDB pomDB;

    /**
     * Creates new form PomodoroGUI
     */
    public PomodoroGUI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonAniadirEmpleado = new javax.swing.JButton();
        botonEliminarEmpleado = new javax.swing.JButton();
        botonAniadirTarea = new javax.swing.JButton();
        botonAsignarTarea = new javax.swing.JButton();
        botonEliminarTarea = new javax.swing.JButton();
        botonDesasignarEmpleado = new javax.swing.JButton();
        botonModificarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAniadirPlato = new javax.swing.JButton();
        botonEliminarPlato = new javax.swing.JButton();
        botonModificarPlato = new javax.swing.JButton();
        botonModificarMenu = new javax.swing.JButton();
        botonEliminarMenu = new javax.swing.JButton();
        botonAniadirMenu = new javax.swing.JButton();
        botonAsignarIngredientes = new javax.swing.JButton();
        botonAsignarMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonAniadirProveedor = new javax.swing.JButton();
        botonEliminarProveedor = new javax.swing.JButton();
        botonModificarProveedor = new javax.swing.JButton();
        botonAniadirIngrediente = new javax.swing.JButton();
        botonEliminarIngrediente = new javax.swing.JButton();
        botonModificarIngrediente = new javax.swing.JButton();
        botonEstablecerIngrediente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonMostrarBD = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAniadirEmpleado.setText("Añadir Empleado");
        botonAniadirEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirEmpleadoActionPerformed(evt);
            }
        });

        botonEliminarEmpleado.setText("Eliminar Empleado");
        botonEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });

        botonAniadirTarea.setText("Añadir Tarea");
        botonAniadirTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirTarea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirTareaActionPerformed(evt);
            }
        });

        botonAsignarTarea.setText("Asignar Empleado a una Tarea");
        botonAsignarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarTareaActionPerformed(evt);
            }
        });

        botonEliminarTarea.setText("Eliminar Tarea");
        botonEliminarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTareaActionPerformed(evt);
            }
        });

        botonDesasignarEmpleado.setText("Desasignar Empleado a una Tarea");
        botonDesasignarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDesasignarEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDesasignarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesasignarEmpleadoActionPerformed(evt);
            }
        });

        botonModificarEmpleado.setText("Modificar Empleado");
        botonModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(botonAniadirEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(botonDesasignarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAsignarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(botonAniadirTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAniadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAsignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDesasignarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(botonAniadirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Gestión de Empleados", jPanel1);

        botonAniadirPlato.setText("Añadir Plato");
        botonAniadirPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirPlato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirPlatoActionPerformed(evt);
            }
        });

        botonEliminarPlato.setText("Eliminar Plato");
        botonEliminarPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPlatoActionPerformed(evt);
            }
        });

        botonModificarPlato.setText("Modificar Plato");
        botonModificarPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPlatoActionPerformed(evt);
            }
        });

        botonModificarMenu.setText("Modificar Menu");
        botonModificarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarMenuActionPerformed(evt);
            }
        });

        botonEliminarMenu.setText("Eliminar Menu");
        botonEliminarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMenuActionPerformed(evt);
            }
        });

        botonAniadirMenu.setText("Añadir Menu");
        botonAniadirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirMenuActionPerformed(evt);
            }
        });

        botonAsignarIngredientes.setText("Asignar Ingredientes al Plato");
        botonAsignarIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarIngredientesActionPerformed(evt);
            }
        });

        botonAsignarMenu.setText("Asignar Plato a un Menú");
        botonAsignarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEliminarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(botonAniadirPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(botonAsignarIngredientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(botonAniadirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(botonAsignarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAniadirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(botonModificarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAniadirPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAsignarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAsignarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Menus", jPanel2);

        botonAniadirProveedor.setText("Añadir Proveedor");
        botonAniadirProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirProveedorActionPerformed(evt);
            }
        });

        botonEliminarProveedor.setText("Eliminar Proveedor");
        botonEliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProveedorActionPerformed(evt);
            }
        });

        botonModificarProveedor.setText("Modificar Proveedor");
        botonModificarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProveedorActionPerformed(evt);
            }
        });

        botonAniadirIngrediente.setText("Añadir Ingrediente");
        botonAniadirIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirIngredienteActionPerformed(evt);
            }
        });

        botonEliminarIngrediente.setText("Eliminar Ingrediente");
        botonEliminarIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarIngredienteActionPerformed(evt);
            }
        });

        botonModificarIngrediente.setText("Modificar Ingrediente");
        botonModificarIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarIngredienteActionPerformed(evt);
            }
        });

        botonEstablecerIngrediente.setText("Establecer Ingrediente Provisto ");
        botonEstablecerIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstablecerIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEstablecerIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEliminarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(botonAniadirProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(botonEstablecerIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botonModificarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(botonAniadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(botonAniadirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(botonEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(botonModificarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAniadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModificarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEstablecerIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Proveedores", jPanel3);

        botonSalir.setBackground(new java.awt.Color(210, 62, 52));
        botonSalir.setText("Salir");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonMostrarBD.setText("Mostrar Base de Datos");
        botonMostrarBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarBDActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BASE DE DATOS DEL RESTAURANTE POMODORO");
        titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMostrarBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrarBD, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        JOptionPane.showMessageDialog(this, "Hasta pronto!");
        try {
            pomDB.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(PomodoroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAniadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirEmpleadoActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Empleado");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al añadir un empleado");
        }
    }//GEN-LAST:event_botonAniadirEmpleadoActionPerformed

    private void botonMostrarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarBDActionPerformed
        String db = "", tabla = "";
        String[] options = {"Empleado", "Tarea", "Menu", "Plato", "Proveedor", "Ingrediente",
                          "menu_contiene_plato", "plato_contiene_ing", "provee", "asignacion"};
        tabla = (String) JOptionPane.showInputDialog(null,"Selecciona una tabla", "Tablas...",
                                            JOptionPane.QUESTION_MESSAGE,null,options, options[0]);
        try {
            pomDB.mostrarTabla(tabla);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "La tabla que has introducido no existe");
        }
    }//GEN-LAST:event_botonMostrarBDActionPerformed

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        String salida = "";
        try {
            salida = pomDB.eliminarTabla("Empleado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el empleado");
        }
        JOptionPane.showMessageDialog(this, salida);  
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void botonAsignarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarTareaActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("asignacion");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al asignar tarea");
        }
    }//GEN-LAST:event_botonAsignarTareaActionPerformed

    private void botonAniadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirTareaActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Tarea");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar una tarea nueva");
        }
    }//GEN-LAST:event_botonAniadirTareaActionPerformed

    private void botonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTareaActionPerformed
        String salida = "";
        try {
            salida = pomDB.eliminarTabla("Tarea");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la tarea");
        }
        JOptionPane.showMessageDialog(this, salida); 
    }//GEN-LAST:event_botonEliminarTareaActionPerformed

    private void botonDesasignarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesasignarEmpleadoActionPerformed
        String salida = "";
        try {
            salida = pomDB.eliminarTabla("asignacion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al desasignar empleado");
        }
        JOptionPane.showMessageDialog(this, salida); 
    }//GEN-LAST:event_botonDesasignarEmpleadoActionPerformed

    private void botonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEmpleadoActionPerformed
        String db = "";
        try {
            db = pomDB.modificarTabla("Empleado");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar un empleado");
        }
    }//GEN-LAST:event_botonModificarEmpleadoActionPerformed

    
    
    
    
    private void botonAniadirPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirPlatoActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Plato");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al añadir un plato");
        }
    }//GEN-LAST:event_botonAniadirPlatoActionPerformed

    private void botonEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPlatoActionPerformed
        String salida = "";
        try {
            salida = pomDB.eliminarTabla("Plato");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar plato");
        }
        JOptionPane.showMessageDialog(this, salida);
    }//GEN-LAST:event_botonEliminarPlatoActionPerformed

    private void botonModificarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPlatoActionPerformed
        String db = "";
        try {
            db = pomDB.modificarTabla("Plato");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar plato");
        }
    }//GEN-LAST:event_botonModificarPlatoActionPerformed

    private void botonModificarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarMenuActionPerformed
        String db = "";
        try {
            db = pomDB.modificarTabla("Menu");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar menú");
        }
    }//GEN-LAST:event_botonModificarMenuActionPerformed

    private void botonEliminarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMenuActionPerformed
        String salida = "";
        try {
            salida = pomDB.eliminarTabla("Menu");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar menú");
        }
        JOptionPane.showMessageDialog(this, salida);
    }//GEN-LAST:event_botonEliminarMenuActionPerformed

    private void botonAniadirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirMenuActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Menu");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al añadir menú");
        }
    }//GEN-LAST:event_botonAniadirMenuActionPerformed

    private void botonAsignarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarIngredientesActionPerformed
        try {
            pomDB.insertarIngredientePlato();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer ingredientes provistos");
        }
    }//GEN-LAST:event_botonAsignarIngredientesActionPerformed

    private void botonAsignarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarMenuActionPerformed
        try {
            pomDB.insertarPlatosMenu();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer platos del menu");
        }
    }//GEN-LAST:event_botonAsignarMenuActionPerformed

    
    
    
    
    private void botonAniadirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirProveedorActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Proveedor");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al insertar proveedor");
        }
    }//GEN-LAST:event_botonAniadirProveedorActionPerformed

    private void botonEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProveedorActionPerformed
        String db = "";
        try {
            db = pomDB.eliminarTabla("Proveedor");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar proveedor");
        }
    }//GEN-LAST:event_botonEliminarProveedorActionPerformed

    private void botonModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProveedorActionPerformed
        String db = "";
        try {
            db = pomDB.modificarTabla("Proveedor");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar proveedor");
        }
    }//GEN-LAST:event_botonModificarProveedorActionPerformed

    private void botonAniadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirIngredienteActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Ingrediente");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al añadir ingrediente");
        }
    }//GEN-LAST:event_botonAniadirIngredienteActionPerformed

    private void botonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarIngredienteActionPerformed
        String db = "";
        try {
            db = pomDB.insertarTabla("Ingrediente");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al eliminar ingrediente");
        }
    }//GEN-LAST:event_botonEliminarIngredienteActionPerformed

    private void botonModificarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarIngredienteActionPerformed
        String db = "";
        try {
            db = pomDB.modificarTabla("Ingrediente");
            JOptionPane.showMessageDialog(this, db);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al modificar ingrediente");
        }
    }//GEN-LAST:event_botonModificarIngredienteActionPerformed

    private void botonEstablecerIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerIngredienteActionPerformed
        try {
            pomDB.establecerIngrediente();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer ingredientes provistos");
        }
    }//GEN-LAST:event_botonEstablecerIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PomodoroGUI().setVisible(true);
                pomDB = new PomodoroDB();
                pomDB.crearConexion();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAniadirEmpleado;
    private javax.swing.JButton botonAniadirIngrediente;
    private javax.swing.JButton botonAniadirMenu;
    private javax.swing.JButton botonAniadirPlato;
    private javax.swing.JButton botonAniadirProveedor;
    private javax.swing.JButton botonAniadirTarea;
    private javax.swing.JButton botonAsignarIngredientes;
    private javax.swing.JButton botonAsignarMenu;
    private javax.swing.JButton botonAsignarTarea;
    private javax.swing.JButton botonDesasignarEmpleado;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JButton botonEliminarIngrediente;
    private javax.swing.JButton botonEliminarMenu;
    private javax.swing.JButton botonEliminarPlato;
    private javax.swing.JButton botonEliminarProveedor;
    private javax.swing.JButton botonEliminarTarea;
    private javax.swing.JButton botonEstablecerIngrediente;
    private javax.swing.JButton botonModificarEmpleado;
    private javax.swing.JButton botonModificarIngrediente;
    private javax.swing.JButton botonModificarMenu;
    private javax.swing.JButton botonModificarPlato;
    private javax.swing.JButton botonModificarProveedor;
    private javax.swing.JButton botonMostrarBD;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
