/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pomodorogui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author jose26398
 */
public class PomodoroGUI extends javax.swing.JFrame {

    static PomodoroDB pomDB;

    /**
     * Creates new form PomodoroGUI
     */
    public PomodoroGUI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setTitle("Gestion Pomodoro");
        //this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonAniadirEmpleado = new javax.swing.JButton();
        botonEliminarEmpleado = new javax.swing.JButton();
        botonAniadirTarea = new javax.swing.JButton();
        botonAsignarTarea = new javax.swing.JButton();
        botonEliminarTarea = new javax.swing.JButton();
        botonDesasignarEmpleado = new javax.swing.JButton();
        botonModificarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonAniadirPlato = new javax.swing.JButton();
        botonEliminarPlato = new javax.swing.JButton();
        botonModificarPlato = new javax.swing.JButton();
        botonModificarMenu = new javax.swing.JButton();
        botonEliminarMenu = new javax.swing.JButton();
        botonAniadirMenu = new javax.swing.JButton();
        botonAsignarIngredientes = new javax.swing.JButton();
        botonAsignarMenu = new javax.swing.JButton();
        botonDesasignarIngredientes = new javax.swing.JButton();
        botonDesasignarMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        botonAniadirProveedor = new javax.swing.JButton();
        botonEliminarProveedor = new javax.swing.JButton();
        botonModificarProveedor = new javax.swing.JButton();
        botonAniadirIngrediente = new javax.swing.JButton();
        botonEstablecerIngrediente = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonMostrarBD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAniadirEmpleado.setText("Añadir Empleado");
        botonAniadirEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirEmpleadoActionPerformed(evt);
            }
        });

        botonEliminarEmpleado.setText("Eliminar Empleado");
        botonEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });

        botonAniadirTarea.setText("Añadir Tarea");
        botonAniadirTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirTarea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirTareaActionPerformed(evt);
            }
        });

        botonAsignarTarea.setText("Asignar Empleado a una Tarea");
        botonAsignarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarTareaActionPerformed(evt);
            }
        });

        botonEliminarTarea.setText("Eliminar Tarea");
        botonEliminarTarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTareaActionPerformed(evt);
            }
        });

        botonDesasignarEmpleado.setText("Desasignar Empleado a una Tarea");
        botonDesasignarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDesasignarEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDesasignarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesasignarEmpleadoActionPerformed(evt);
            }
        });

        botonModificarEmpleado.setText("Modificar Empleado");
        botonModificarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAniadirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDesasignarEmpleado)
                    .addComponent(botonAsignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAniadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAniadirEmpleado, botonAniadirTarea, botonAsignarTarea, botonDesasignarEmpleado, botonEliminarEmpleado, botonEliminarTarea, botonModificarEmpleado});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(botonAniadirEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAniadirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAsignarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonDesasignarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Empleados", jPanel1);

        botonAniadirPlato.setText("Añadir Plato");
        botonAniadirPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirPlato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirPlatoActionPerformed(evt);
            }
        });

        botonEliminarPlato.setText("Eliminar Plato");
        botonEliminarPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPlatoActionPerformed(evt);
            }
        });

        botonModificarPlato.setText("Modificar Plato");
        botonModificarPlato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPlatoActionPerformed(evt);
            }
        });

        botonModificarMenu.setText("Modificar Menu");
        botonModificarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarMenuActionPerformed(evt);
            }
        });

        botonEliminarMenu.setText("Eliminar Menu");
        botonEliminarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMenuActionPerformed(evt);
            }
        });

        botonAniadirMenu.setText("Añadir Menu");
        botonAniadirMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirMenuActionPerformed(evt);
            }
        });

        botonAsignarIngredientes.setText("Asignar Ingredientes al Plato");
        botonAsignarIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarIngredientesActionPerformed(evt);
            }
        });

        botonAsignarMenu.setText("Asignar Plato a un Menú");
        botonAsignarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAsignarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarMenuActionPerformed(evt);
            }
        });

        botonDesasignarIngredientes.setText("Desasignar Ingredientes al Plato");
        botonDesasignarIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDesasignarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesasignarIngredientesActionPerformed(evt);
            }
        });

        botonDesasignarMenu.setText("Desasignar Plato a un Menú");
        botonDesasignarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDesasignarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDesasignarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDesasignarIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonEliminarPlato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonAniadirPlato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonModificarPlato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonAsignarIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonAniadirMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonModificarMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonAsignarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(botonDesasignarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAniadirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                        .addComponent(botonEliminarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(botonModificarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAniadirPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificarPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAsignarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAsignarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonDesasignarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDesasignarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Menus", jPanel2);

        botonAniadirProveedor.setText("Añadir Proveedor");
        botonAniadirProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirProveedorActionPerformed(evt);
            }
        });

        botonEliminarProveedor.setText("Eliminar Proveedor");
        botonEliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProveedorActionPerformed(evt);
            }
        });

        botonModificarProveedor.setText("Modificar Proveedor");
        botonModificarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProveedorActionPerformed(evt);
            }
        });

        botonAniadirIngrediente.setText("Añadir Ingrediente");
        botonAniadirIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAniadirIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAniadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirIngredienteActionPerformed(evt);
            }
        });

        botonEstablecerIngrediente.setText("Establecer Ingrediente Provisto ");
        botonEstablecerIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstablecerIngrediente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEstablecerIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEliminarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAniadirProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAniadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEstablecerIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAniadirIngrediente, botonAniadirProveedor, botonEliminarProveedor, botonModificarProveedor});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(botonAniadirProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(botonEliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(botonModificarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(botonAniadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(botonEstablecerIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión de Proveedores", jPanel3);

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BASE DE DATOS DEL RESTAURANTE POMODORO");
        titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        botonSalir.setBackground(new java.awt.Color(210, 62, 52));
        botonSalir.setText("Salir");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonMostrarBD.setText("Mostrar Base de Datos");
        botonMostrarBD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMostrarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonMostrarBD, botonSalir});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botonMostrarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres cerrar el programa?");
        try {
            pomDB.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(PomodoroGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAniadirEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirEmpleadoActionPerformed
        pomDB.gEmp.insertarEmpleado(this);
    }//GEN-LAST:event_botonAniadirEmpleadoActionPerformed

    private void botonMostrarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarBDActionPerformed
        String db = "", tabla = "";
        String[] options = {"Empleado", "Tarea", "Menu", "Plato", "Proveedor", "Ingrediente",
            "menu_contiene_plato", "plato_contiene_ing", "provee", "asignacion"};
        tabla = (String) JOptionPane.showInputDialog(null, "Selecciona una tabla", "Tablas...",
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        try {
            pomDB.mostrarTabla(tabla);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "La tabla que has introducido no existe");
        }
    }//GEN-LAST:event_botonMostrarBDActionPerformed

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        pomDB.gEmp.eliminarEmpleado(this);
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void botonAsignarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarTareaActionPerformed
        try {
            pomDB.gEmp.asignarEmpleadoTarea();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al asignar empleado a una tarea");
        }
    }//GEN-LAST:event_botonAsignarTareaActionPerformed

    private void botonAniadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirTareaActionPerformed
        pomDB.gEmp.insertarTarea(this);
    }//GEN-LAST:event_botonAniadirTareaActionPerformed

    private void botonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTareaActionPerformed
        pomDB.gEmp.eliminarTarea(this);
    }//GEN-LAST:event_botonEliminarTareaActionPerformed

    private void botonDesasignarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesasignarEmpleadoActionPerformed
        try {
            pomDB.gEmp.desasignarEmpleadoTarea();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al desasignar empleado a una tarea");
        }
    }//GEN-LAST:event_botonDesasignarEmpleadoActionPerformed

    private void botonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEmpleadoActionPerformed
        pomDB.gEmp.modificarEmpleado(this);
    }//GEN-LAST:event_botonModificarEmpleadoActionPerformed


    private void botonAniadirPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirPlatoActionPerformed
        pomDB.gMenu.insertarPlato(this);
    }//GEN-LAST:event_botonAniadirPlatoActionPerformed

    private void botonEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPlatoActionPerformed
        pomDB.gMenu.eliminarPlato(this);
    }//GEN-LAST:event_botonEliminarPlatoActionPerformed

    private void botonModificarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPlatoActionPerformed
        pomDB.gMenu.modificarPlato(this);
    }//GEN-LAST:event_botonModificarPlatoActionPerformed

    private void botonModificarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarMenuActionPerformed
        pomDB.gMenu.modificarMenu(this);
    }//GEN-LAST:event_botonModificarMenuActionPerformed

    private void botonEliminarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMenuActionPerformed
        pomDB.gMenu.eliminarMenu(this);
    }//GEN-LAST:event_botonEliminarMenuActionPerformed

    private void botonAniadirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirMenuActionPerformed
        pomDB.gMenu.insertarMenu(this);
    }//GEN-LAST:event_botonAniadirMenuActionPerformed

    private void botonAsignarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarIngredientesActionPerformed
        try {
            pomDB.gMenu.asignarIngredientePlato();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer ingredientes provistos");
        }
    }//GEN-LAST:event_botonAsignarIngredientesActionPerformed

    private void botonAsignarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarMenuActionPerformed
        try {
            pomDB.gMenu.asignarPlatosMenu();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer platos del menu");
        }
    }//GEN-LAST:event_botonAsignarMenuActionPerformed


    private void botonAniadirProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirProveedorActionPerformed
        
        pomDB.gProv.insertarProveedor(this);
    }//GEN-LAST:event_botonAniadirProveedorActionPerformed

    private void botonEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProveedorActionPerformed
        
        pomDB.gProv.eliminarProveedor(this);
    }//GEN-LAST:event_botonEliminarProveedorActionPerformed

    private void botonModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProveedorActionPerformed
        
        pomDB.gProv.modificarProveedor(this);
    }//GEN-LAST:event_botonModificarProveedorActionPerformed

    private void botonAniadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirIngredienteActionPerformed
        
        pomDB.gProv.insertarIngrediente(this);
    }//GEN-LAST:event_botonAniadirIngredienteActionPerformed

    
    
    private void botonDesasignarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesasignarIngredientesActionPerformed
        try {
            pomDB.gMenu.desasignarIngredientesPlato();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer ingredientes provistos");
        }
    }//GEN-LAST:event_botonDesasignarIngredientesActionPerformed

    private void botonDesasignarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesasignarMenuActionPerformed
        try {
            pomDB.gMenu.desasignarPlatosMenu();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al establecer ingredientes provistos");
        }
    }//GEN-LAST:event_botonDesasignarMenuActionPerformed

    private void botonEstablecerIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerIngredienteActionPerformed
    
        pomDB.gProv.provee(this);
    }//GEN-LAST:event_botonEstablecerIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PomodoroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                pomDB = new PomodoroDB();
                new PomodoroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAniadirEmpleado;
    private javax.swing.JButton botonAniadirIngrediente;
    private javax.swing.JButton botonAniadirMenu;
    private javax.swing.JButton botonAniadirPlato;
    private javax.swing.JButton botonAniadirProveedor;
    private javax.swing.JButton botonAniadirTarea;
    private javax.swing.JButton botonAsignarIngredientes;
    private javax.swing.JButton botonAsignarMenu;
    private javax.swing.JButton botonAsignarTarea;
    private javax.swing.JButton botonDesasignarEmpleado;
    private javax.swing.JButton botonDesasignarIngredientes;
    private javax.swing.JButton botonDesasignarMenu;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JButton botonEliminarMenu;
    private javax.swing.JButton botonEliminarPlato;
    private javax.swing.JButton botonEliminarProveedor;
    private javax.swing.JButton botonEliminarTarea;
    private javax.swing.JButton botonEstablecerIngrediente;
    private javax.swing.JButton botonModificarEmpleado;
    private javax.swing.JButton botonModificarMenu;
    private javax.swing.JButton botonModificarPlato;
    private javax.swing.JButton botonModificarProveedor;
    private javax.swing.JButton botonMostrarBD;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
